spiderJson = {"nodes":[
{"weight":9,"rank":13.57228316310467, "id":1, "url":"http://www.topfreeweb.net"},
{"weight":9,"rank":19.0, "id":9, "url":"http://www.topfreeweb.net/index.php/download"},
{"weight":9,"rank":13.57228316310467, "id":10, "url":"http://www.topfreeweb.net/index.php/help"},
{"weight":2,"rank":0.0, "id":13, "url":"http://www.topfreeweb.net/index.php/download/info?aid=187"},
{"weight":1,"rank":0.0, "id":15, "url":"http://www.topfreeweb.net/index.php/download/info?aid=184"},
{"weight":1,"rank":0.0, "id":17, "url":"http://www.topfreeweb.net/index.php/download/info?aid=170"},
{"weight":2,"rank":0.0, "id":18, "url":"http://www.topfreeweb.net/index.php/download/info?aid=188"},
{"weight":1,"rank":0.0, "id":19, "url":"http://www.topfreeweb.net/index.php/download/info?aid=185"},
{"weight":1,"rank":0.0, "id":20, "url":"http://www.topfreeweb.net/index.php/download/info?aid=181"}],
"links":[
{"source":0,"target":0,"value":3},
{"source":0,"target":1,"value":3},
{"source":0,"target":2,"value":3},
{"source":1,"target":0,"value":3},
{"source":1,"target":1,"value":3},
{"source":1,"target":2,"value":3},
{"source":1,"target":3,"value":3},
{"source":1,"target":4,"value":3},
{"source":1,"target":5,"value":3},
{"source":1,"target":6,"value":3},
{"source":1,"target":7,"value":3},
{"source":1,"target":8,"value":3},
{"source":2,"target":0,"value":3},
{"source":2,"target":1,"value":3},
{"source":2,"target":2,"value":3},
{"source":3,"target":0,"value":3},
{"source":3,"target":1,"value":3},
{"source":3,"target":2,"value":3},
{"source":3,"target":3,"value":3},
{"source":4,"target":0,"value":3},
{"source":4,"target":1,"value":3},
{"source":4,"target":2,"value":3},
{"source":5,"target":0,"value":3},
{"source":5,"target":1,"value":3},
{"source":5,"target":2,"value":3},
{"source":6,"target":0,"value":3},
{"source":6,"target":1,"value":3},
{"source":6,"target":2,"value":3},
{"source":6,"target":6,"value":3},
{"source":7,"target":0,"value":3},
{"source":7,"target":1,"value":3},
{"source":7,"target":2,"value":3},
{"source":8,"target":0,"value":3},
{"source":8,"target":1,"value":3},
{"source":8,"target":2,"value":3}]};